#! /usr/bin/python3
str1 = 'My name is leelakrishna'
str2 = 'learning python'
str3 = '0xa'
str4 = 'leelakrishna'
print('str2--->', str2)
print('str1--->', str1)
print('str1+str2=', str1+str2)
print('str1*3=', str1*3)
print('My name is %s and working hours %s' %('leelakrishna',29))
#print('My name is %s and working hours %d' %('leelakrishna', 29))
print('My name is %s and working hours %x' %('leelakrishna', 0xa))
print('My name is %s and working hours %f' %('leelakrishna', 66.00))
print('My name is %s and working hours %u' %('leelakrishna', 66.00))
print('My name is %s and working hours %X' %('leelakrishna', 66.00))
print('str1.capitalize()-->', str1.capitalize())
print('str1.center(20, k)--->', str1.center(20, 'k'))
print('str1.count(l)--->', str1.count('l'))
#print('str3.decode(UTF-8)--->', str3.decode('UTF-8'))
print('str3.encode(UTF-8)--->', str3.encode('UTF-8'))
print('str1.endswith("krishna")--->', str1.endswith("krishna"))
print('str1.expandtabs()--->', str1.expandtabs())
print('str1.index(l)--->', str1.index('l'))
print('str1.isalnum()--->', str1.isalnum())
print('str1.isalpha()--->', str1.isalpha())
print('str2.isdigit()---->', str2.isdigit())
print('str2.islower()--->', str2.islower())
print('str2.isnumric()--->', str2.isnumeric())
print('str2.isspace()--->', str2.isspace())
print('str2.istitle()--->', str2.istitle())
print('str2.isupper()--->', str2.isupper())
print('st2.join(str1)--->', str2.join(str1))
print('len(str2)--->', len(str2))
print('str1.lower()--->', str1.lower())
print('str2.upper()--->', str2.upper())
print('min(str2)--->', min(str2))
print('max(str2)--->', max(str2))
print('str2.rfind(l)-->', str2.rfind('l'))
print('str2.rindex(l)--->', str2.rindex('l'))
print('str2.rjust(20,0)--->', str2.rjust(20, '0'))
print('str4.rstrip()--->', str4.rstrip())
print('str4.strip()--->', str4.strip())
from string import Template
s = Template('My name is $a, hi $a welocone to program')
s.substitute(a='leelakrishna')
#print('s-->', s)
